#!/bin/bash

kernel="$(uname)"
if [ $kernel == "Darwin" ]; then
    os="macOS"
elif [ $kernel == "Linux" ]; then
    os="Linux"
else
    echo "Kernel unknown!"
    exit 1
fi

init_config() {
if [ -d ~/.config ]; then
    TEMP=$(mktemp -d)
    cp -r ~/.config/* $TEMP
    rm -rf ~/.config/*
    setup_$os
    cp -rn $TEMP/* ~/.config
    rm -rf $TEMP
else
    mkdir -p ~/.config
    setup_$os
fi
}

setup_Linux() {
    echo "Running Linux setup..."
    echo "Making symbolic link: ~/.dotfiles/zsh to ~/.config..."
    ln -s ~/.dotfiles/zsh ~/.config
    echo "Making symbolic link: ~/.dotfiles/tmux to ~/.config..."
    ln -s ~/.dotfiles/tmux ~/.config
    echo "Making symbolic link: ~/.dotfiles/sway to ~/.config..."
    ln -s ~/.dotfiles/sway ~/.config
    echo "Making symbolic link: ~/.dotfiles/foot to ~/.config..."
    ln -s ~/.dotfiles/foot ~/.config
    echo "Making symbolic link: ~/.dotfiles/.vimrc to ~/.vimrc..."
    ln -s ~/.dotfiles/.vimrc ~/.vimrc
    echo "Making symbolic link: ~/.dotfiles/.zprofile to ~/.zprofile..."
    ln -s ~/.dotfiles/.zprofile ~/.zprofile
    mkdir ~/.config/zsh/plugins
    echo "All symbolic links created. Restart your shell."
}

setup_macOS() {
    echo "Running macOS setup..."
    echo "Making symbolic link: ~/.dotfiles/zsh to ~/.config..."
    create_symlink $HOME/.dotfiles/zsh ~/.config/zsh
    echo "Making symbolic link: ~/.dotfiles/tmux to ~/.config..."
    create_symlink ~/.dotfiles/tmux ~/.config/tmux
    echo "Making symbolic link: ~/.dotfiles/.vimrc to ~/.vimrc..."
    create_symlink ~/.dotfiles/.vimrc ~/.vimrc
    echo "Making symbolic link: ~/.dotfiles/.zprofile to ~/.zprofile..."
    create_symlink ~/.dotfiles/.zprofile ~/.zprofile
    [ -d ~/.config/zsh/plugins ] || mkdir ~/.config/zsh/plugins
    echo "All symbolic links created. Restart your shell."
}

create_symlink() {
    source_path=$1
    target_path=$2

    if [ -L $target_path ] && [ "$(readlink -f $target_path)" = "$(eval echo "$source_path")" ]; then
    	echo "Symbolic link already exists: $target_path"
    else
	if [ -e $target_path ]; then
            rm -rf $target_path || { echo "Failed to remove existing file: $target_path"; return 1; }
	fi
    	ln -s $source_path $target_path || { echo "Failed to create symbolic link: $source_path --> $target_path"; return 1; }
        echo "Created symbolic link: $source_path --> $target_path"
    fi
}

init_config
